name: template_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  auto_route: ^10.2.0
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  mobx: ^2.4.1
  flutter_mobx: ^2.2.1+1
  flutter_dotenv: ^6.0.0
  get_it: ^9.0.5
  json_annotation: ^4.9.0
  retrofit: ^4.9.0
  shimmer: ^3.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  mobx_codegen: ^2.7.0
  retrofit_generator: ^10.1.2
  json_serializable: ^6.11.1
  auto_route_generator: ^10.2.5
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  # Environment files
  assets:
    - .env
    - .env.dev
    - .env.prod
  
  # Fonts
  fonts:
    - family: Futurama
      fonts:
        - asset: assets/fonts/futurama-font.ttf
    - family: FuturamaTitle
      fonts:
        - asset: assets/fonts/futurama-title.ttf
